# Generated by Django 4.1.7 on 2023-03-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Smartify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('fimg', models.CharField(max_length=120)),
                ('simg', models.CharField(max_length=120)),
                ('timg', models.CharField(max_length=120)),
                ('intro', models.TextField()),
                ('oimg', models.CharField(max_length=120)),
            ],
        ),
    ]
