# Generated by Django 4.1.7 on 2023-03-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartify', '0003_smartify_fpara_smartify_outro_smartify_spara'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartify',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smartify',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
