# Generated by Django 4.1.7 on 2023-03-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartify', '0005_remove_smartify_date_smartify_datenew'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartify',
            name='dateNew',
        ),
        migrations.AddField(
            model_name='smartify',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
