from django.db import models

class Smartify(models.Model):
    title = models.CharField(max_length=120, blank=True, null=True)
    date= models.DateField(blank=True, null=True)
    time = models.TimeField(blank=True, null=True)
    fimg = models.CharField(max_length=120, blank=True, null=True)
    introFirst = models.TextField( blank=True, null=True)
    introSecond = models.TextField( blank=True, null=True)
    introThird = models.TextField( blank=True, null=True)
    introFourth = models.TextField( blank=True, null=True)
    simg= models.CharField(max_length=120, blank=True, null=True)
    fparaBOne = models.TextField( blank=True, null=True)
    fparaBTwo = models.TextField( blank=True, null=True)
    fparaBThree = models.TextField( blank=True, null=True)
    fparaBFour = models.TextField( blank=True, null=True)
    fparaBFive = models.TextField( blank=True, null=True)
    fparaBSix = models.TextField( blank=True, null=True)
    fparaBSeven = models.TextField( blank=True, null=True)
    fparaOne = models.TextField( blank=True, null=True)
    fparaTwo = models.TextField( blank=True, null=True)
    fparaThree = models.TextField( blank=True, null=True)
    fparaFour = models.TextField( blank=True, null=True)
    fparaFive = models.TextField( blank=True, null=True)
    fparaSix = models.TextField( blank=True, null=True)
    fparaSeven = models.TextField( blank=True, null=True)
    fparaEight = models.TextField( blank=True, null=True)
    fparaNine = models.TextField( blank=True, null=True)
    fparaTen = models.TextField( blank=True, null=True)
    fparaEleven = models.TextField( blank=True, null=True)
    fparaTwelve = models.TextField( blank=True, null=True)
    fparaThirteen = models.TextField( blank=True, null=True)
    fparaFourteen = models.TextField( blank=True, null=True)
    fparaFifteen = models.TextField( blank=True, null=True)
    fparaSixteen = models.TextField( blank=True, null=True)
    fparaSeventeen = models.TextField( blank=True, null=True)
    fparaEighteen = models.TextField( blank=True, null=True)
    timg = models.CharField(max_length=120, blank=True, null=True)
    sparaOne = models.TextField( blank=True, null=True)
    sparaTwo = models.TextField( blank=True, null=True)
    sparaThree = models.TextField( blank=True, null=True)
    sparaFour = models.TextField( blank=True, null=True)
    sparaFive = models.TextField( blank=True, null=True)
    sparaSix = models.TextField( blank=True, null=True)
    sparaSeven = models.TextField( blank=True, null=True)
    sparaEight = models.TextField( blank=True, null=True)
    sparaNine = models.TextField( blank=True, null=True)
    sparaTen = models.TextField( blank=True, null=True)
    sparaEleven = models.TextField( blank=True, null=True)
    sparaTwelve = models.TextField( blank=True, null=True)
    sparaThirteen = models.TextField( blank=True, null=True)
    sparaFourteen = models.TextField( blank=True, null=True)
    sparaFifteen = models.TextField( blank=True, null=True)
    sparaSixteen = models.TextField( blank=True, null=True)
    sparaSeventeen = models.TextField( blank=True, null=True)
    sparaEighteen = models.TextField( blank=True, null=True)
    sparaBOne = models.TextField( blank=True, null=True)
    sparaBTwo = models.TextField( blank=True, null=True)
    sparaBThree = models.TextField( blank=True, null=True)
    sparaBFour = models.TextField( blank=True, null=True)
    sparaBFive = models.TextField( blank=True, null=True)
    sparaBSix = models.TextField( blank=True, null=True)
    sparaBSeven = models.TextField( blank=True, null=True)
    oimg = models.CharField(max_length=120, blank=True, null=True)
    outro = models.TextField( blank=True, null=True)



    def __str__(self):
        return self.title
